export const UserConstants = {
    VERIFYING_USER_LOGIN: 'VERIFYING_USER_LOGIN',
    VERIFYING_USER_LOGIN_SUCCESS: 'VERIFYING_USER_LOGIN_SUCCESS',
    VERIFYING_USER_LOGIN_FAILURE: 'VERIFYING_USER_LOGIN_FAILURE',
    USER_LOGGING_IN: 'USER_LOGGING_IN',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGING_OUT: 'USER_LOGGING_OUT',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FALIURE: 'USER_SIGNUP_FALIURE',
    USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
    USER_EMAIL_VERIFICATION_FALIURE: 'USER_EMAIL_VERIFICATION_FALIURE',
    USER_AWAITING_EMAIL_VERIFICATION: 'USER_AWAITING_EMAIL_VERIFICATION',
    USER_AWAITING_PASSWORD_RESET_VERIFICATION: 'USER_AWAITING_PASSWORD_RESET_VERIFICATION',
    USER_PASSWORD_RESET_FAILURE: 'USER_PASSWORD_RESET_FAILURE',
    USER_PASSWORD_RESET_SUCCESS: 'USER_PASSWORD_RESET_SUCCESS',
    USER_AWAITING_TERMINATION: 'USER_AWAITING_TERMINATION',
    USER_TERMINATION_FAILURE: 'USER_TERMINATION_FAILURE',
    USER_TERMINATION_SUCCESS: 'USER_TERMINATION_SUCCESS',
    CLEAR_AUTH_ERRORS: 'CLEAR_AUTH_ERRORS',
    GET_AUTH_ERRORS: 'GET_AUTH_ERRORS',
    CLEAR_AUTH_STATE: 'CLEAR_AUTH_STATE',
    LOADING_USER: 'LOADING_USER',
    LOADING_USER_FAILURE: 'LOADING_USER_FAILURE',
    LOADING_USER_SUCCESS: 'LOADING_USER_SUCCESS',
    HASHING_TO_STORAGE: 'HASHING_TO_STORAGE',
    HASHED_TO_STORAGE: 'HASHED_TO_STORAGE',
    HASHING_TO_STORAGE_FAIL: 'HASHING_TO_STORAGE_FAIL',
    REMOVED_FROM_STORAGE: 'REMOVED_FROM_STORAGE',
    REMOVING_FROM_STORAGE: 'REMOVING_FROM_STORAGE',
    EDITING_BASIC: 'EDITING_BASIC',
    EDITING_BASIC_FAIL: 'EDITING_BASIC_FAIL',
    EDITING_BASIC_SUCCESS: 'EDITING_BASIC_SUCCESS',
    EDITING_PROFILE: 'EDITING_PROFILE',
    EDITING_PROFILE_SUCCESS: 'EDITING_PROFILE_SUCCESS',
    EDITING_PROFILE_FAIL: 'EDITING_PROFILE_FAIL',
    EDITING_MATCH_PROFILE: 'EDITING_MATCH_PROFILE',
    EDITING_MATCH_PROFILE_SUCCESS: 'EDITING_MATCH_PROFILE_SUCCESS',
    EDITING_MATCH_PROFILE_FAIL: 'EDITING_MATCH_PROFILE_FAIL',
    SWIPING_LEFT: 'SWIPING_LEFT',
    SWIPE_LEFT_SUCCESS: 'SWIPE_LEFT_SUCCESS',
    SWIPE_LEFT_FAIL: 'SWIPE_LEFT_FAIL',
    SWIPING_RIGHT: 'SWIPING_RIGHT',
    SWIPE_RIGHT_FAIL: 'SWIPE_RIGHT_FAIL',
    SWIPE_RIGHT_SUCCESS: 'SWIPE_RIGHT_SUCCESS',
    
};

export const RecruiterConstants = {

};

export const SocketConstants = {

};

export const StudentConstants = {
    
};

export const EmployerConstants = {

};

export const JobConstants = {

};
